//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_canabys.html
halflife.wad
chateau.wad
sound/weapons/ak47-2.wav
maps/zm_canabys.bsp
